FROM prasathmahendraraja/alpine-node:${NODE_VERSION}

RUN apk --update add \
    --no-cache \
    --allow-untrusted \
    --repository http://dl-cdn.alpinelinux.org/alpine/v3.15/main \
    git

ENV TZ=America/New_York